export const countryCodes = [
    { name: 'Turkey', dial_code: '+90', code: 'TR', emoji: '🇹🇷' },
    { name: 'United States', dial_code: '+1', code: 'US', emoji: '🇺🇸' },
    { name: 'United Kingdom', dial_code: '+44', code: 'GB', emoji: '🇬🇧' },
    { name: 'Germany', dial_code: '+49', code: 'DE', emoji: '🇩🇪' },
    { name: 'France', dial_code: '+33', code: 'FR', emoji: '🇫🇷' },
    { name: 'Italy', dial_code: '+39', code: 'IT', emoji: '🇮🇹' },
    { name: 'Spain', dial_code: '+34', code: 'ES', emoji: '🇪🇸' },
    { name: 'Russia', dial_code: '+7', code: 'RU', emoji: '🇷🇺' },
    { name: 'United Arab Emirates', dial_code: '+971', code: 'AE', emoji: '🇦🇪' },
    { name: 'Saudi Arabia', dial_code: '+966', code: 'SA', emoji: '🇸🇦' },
    { name: 'Qatar', dial_code: '+974', code: 'QA', emoji: '🇶🇦' },
    { name: 'Netherlands', dial_code: '+31', code: 'NL', emoji: '🇳🇱' },
    { name: 'Belgium', dial_code: '+32', code: 'BE', emoji: '🇧🇪' },
    { name: 'Switzerland', dial_code: '+41', code: 'CH', emoji: '🇨🇭' },
    { name: 'Austria', dial_code: '+43', code: 'AT', emoji: '🇦🇹' },
    { name: 'Greece', dial_code: '+30', code: 'GR', emoji: '🇬🇷' },
    { name: 'Cyprus', dial_code: '+357', code: 'CY', emoji: '🇨🇾' },
    { name: 'Canada', dial_code: '+1', code: 'CA', emoji: '🇨🇦' },
    { name: 'Australia', dial_code: '+61', code: 'AU', emoji: '🇦🇺' },
    { name: 'China', dial_code: '+86', code: 'CN', emoji: '🇨🇳' },
    { name: 'Japan', dial_code: '+81', code: 'JP', emoji: '🇯🇵' },
    { name: 'South Korea', dial_code: '+82', code: 'KR', emoji: '🇰🇷' },
    { name: 'India', dial_code: '+91', code: 'IN', emoji: '🇮🇳' },
    { name: 'Brazil', dial_code: '+55', code: 'BR', emoji: '🇧🇷' },
    { name: 'Mexico', dial_code: '+52', code: 'MX', emoji: '🇲🇽' },
    { name: 'South Africa', dial_code: '+27', code: 'ZA', emoji: '🇿🇦' },
    { name: 'Egypt', dial_code: '+20', code: 'EG', emoji: '🇪🇬' },
    { name: 'Morocco', dial_code: '+212', code: 'MA', emoji: '🇲🇦' },
    { name: 'Israel', dial_code: '+972', code: 'IL', emoji: '🇮🇱' },
    { name: 'Sweden', dial_code: '+46', code: 'SE', emoji: '🇸🇪' },
    { name: 'Norway', dial_code: '+47', code: 'NO', emoji: '🇳🇴' },
    { name: 'Denmark', dial_code: '+45', code: 'DK', emoji: '🇩🇰' },
    { name: 'Finland', dial_code: '+358', code: 'FI', emoji: '🇫🇮' },
    { name: 'Poland', dial_code: '+48', code: 'PL', emoji: '🇵🇱' },
    { name: 'Ukraine', dial_code: '+380', code: 'UA', emoji: '🇺🇦' },
    { name: 'Romania', dial_code: '+40', code: 'RO', emoji: '🇷🇴' },
    { name: 'Bulgaria', dial_code: '+359', code: 'BG', emoji: '🇧🇬' },
    { name: 'Croatia', dial_code: '+385', code: 'HR', emoji: '🇭🇷' },
    { name: 'Serbia', dial_code: '+381', code: 'RS', emoji: '🇷🇸' },
    { name: 'Singapore', dial_code: '+65', code: 'SG', emoji: '🇸🇬' },
    { name: 'Malaysia', dial_code: '+60', code: 'MY', emoji: '🇲🇾' },
    { name: 'Thailand', dial_code: '+66', code: 'TH', emoji: '🇹🇭' },
    { name: 'Indonesia', dial_code: '+62', code: 'ID', emoji: '🇮🇩' },
    { name: 'Vietnam', dial_code: '+84', code: 'VN', emoji: '🇻🇳' },
    { name: 'Philippines', dial_code: '+63', code: 'PH', emoji: '🇵🇭' },
    { name: 'New Zealand', dial_code: '+64', code: 'NZ', emoji: '🇳🇿' },
    { name: 'Argentina', dial_code: '+54', code: 'AR', emoji: '🇦🇷' },
    { name: 'Colombia', dial_code: '+57', code: 'CO', emoji: '🇨🇴' },
    { name: 'Chile', dial_code: '+56', code: 'CL', emoji: '🇨🇱' },
    { name: 'Peru', dial_code: '+51', code: 'PE', emoji: '🇵🇪' }
].sort((a, b) => a.name.localeCompare(b.name));
